// This file is automatically generated by Fuml Studio.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

package ${class.packageName};

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.content.Intent;
import android.util.Log;

//TODO
import net.belehradek.fuml.todolist.fumlandroidtodolist.R;

<#list class.imports as im>
//TODO
</#list>

<#list class.generals as ge>
//${ge.name}
</#list>

${class.visibility} class ${class.name} extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //setContentView(R.layout.${class.nameUnder});

        setContentView(getLayoutId());

        Intent intent = getIntent();
        String[] params = intent.getStringArrayExtra("fUmlActivityParams");

        onStart(params);
    }

    protected int getLayoutId() {
    	int id = getResources().getIdentifier("${class.nameUnder}", "layout", getPackageName());
    	return id;
    }

<#include "javaClassBody.ftl">
}
