<#function packageToPath package>
  <#return package?replace(".", "\\")>
</#function>

<#function isAutoGeneratedOperation operation>
  <#return operation.name == "destroy" || operation.name?contains("$initialization$")>
</#function>

<#function isAutoGeneratedAttribute attribute>
  <#return attribute.name?contains("$initializationFlag$")>
</#function>

<#assign generatedFiles = []>


<#list model.allClasses as class>
<#assign generatedFiles = generatedFiles + [ "src\\main\\java\\${packageToPath(class.packageName)}\\${class.name}.java" ] />

<@createFile filePath="src\\main\\java\\${packageToPath(class.packageName)}" fileName="${class.name}.java">
<#if class.isActivity>
<#include "androidActivityClass.ftl">
<#elseif class.isPersistent>
<#include "androidPersistentClass.ftl">
<#else>
<#include "javaClass.ftl">
</#if>
</@createFile>

</#list>


<#list model.allActivityClasses as class>
<#assign generatedFiles = generatedFiles + [ "src\\main\\res\\layout\\${class.nameUnder}.xml" ] />

<#if class.name != "App">
<@createFile filePath="src\\main\\res\\layout" fileName="${class.nameUnder}.xml">
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="${class.packageName}.${class.name}">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="${class.name}: Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</android.support.constraint.ConstraintLayout>
</@createFile>
</#if>

</#list>


<@createFile fileName="README.md">
This file is automatically generated by Fuml Studio.
Do not modify generated files - YOUR CHANGES WILL BE ERASED!

Add gradle dependecy to Sugar ORM:
to file app\build.gardle in your android project add "compile 'com.github.satyan:sugar:1.3'" to dependencies section
...
dependencies {
	compile 'com.github.satyan:sugar:1.3'
...

Add android activity to AndroidManifest.xml file
for main activity:
<activity android:name="YourActivityName" >
    <intent-filter>
    	<!-- MAIN represents that it is the Main Activity-->
        <action android:name="android.intent.action.MAIN" />
      	<!-- Launcher Denotes that it will be the first launching activity-->
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>
for others activities:
<activity android:name="YourActivityName" />

<meta-data android:name="DATABASE" android:value="sugar.db" />
<meta-data android:name="VERSION" android:value="1" />
<meta-data android:name="QUERY_LOG" android:value="true" />
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.sugar.fuml" />

List of generated files:
${generatedFiles?join("\n")}

</@createFile>