// This file is automatically generated by Fuml Studio.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

package ${class.packageName};

import com.orm.SugarRecord;

${class.visibility} class ${class.name} extends SugarRecord<${class.name}> {
<#include "javaClassAttributes.ftl">
}
