// This file is automatically generated by Fuml Studio.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

package ${class.packageName};

${class.visibility}${class.isAbstract?then(' abstract', '')} class ${class.name}<#if class.generals> extends ${class.generals[0].qualifiedName}</#if> {
<#include "javaClassBody.ftl">
}
