// This file is automatically generated by Fuml Studio.
// Do not modify this file - YOUR CHANGES WILL BE ERASED!

package ${class.packageName};

${class.visibility}${class.isAbstract?then(' abstract', '')} class ${class.name} {
<#include "javaClassBody.ftl">
}
